export const AUTHENTICATE_USER = 'SIGN-IN/EVENT/SIGNIN/AUTHENTICATE_USER';

export const USERNAME_CHANGED = 'SIGN-IN/EVENT/SIGNIN/USERNAME_CHANGED';
export const PASSWORD_CHANGED = 'SIGN-IN/EVENT/SIGNIN/PASSWORD_CHANGED';

export const SET_DRAWER_OPEN = 'SIGN-IN/EVENT/SIGNIN/SET_DRAWER_OPEN';

export const REGISTER_NEW_USER = 'SIGN-IN/EVENT/SIGNIN/REGISTER_NEW_USER';

export const SAVE_SR_NUMBER = 'SIGN-IN/EVENT/SIGNIN/SAVE_SR_NUMBER';

export const CREATE_NEW_USER = 'SIGN-IN/EVENT/SIGNIN/CREATE_NEW_USER';

export const SAVE_SUCCESS_MESSAGE = 'SIGN-IN/EVENT/SIGNIN/SAVE_SUCCESS_MESSAGE';

export const SEND_OTP = 'SIGN-IN/EVENT/SIGNIN/SEND_OTP';

export const SAVE_OTP = 'SIGN-IN/EVENT/SIGNIN/SAVE_OTP';

export const LOGIN_SUCCESS = 'SIGN-IN/EVENT/SIGNIN/LOGIN_SUCCESS';

export const AUTHENTICATION_REVOKED =
  'SIGN-IN/EVENT/SIGNIN/AUTHENTICATION_REVOKED';
